global using System.Net.Http.Headers;
global using System.Security.Claims;
global using System.Text;
global using System.Text.Json;
global using Asp.Versioning;
global using Asp.Versioning.ApiExplorer;
global using MediatR;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ApiExplorer;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Primitives;
global using Microsoft.OpenApi.Models;
global using Paris.RMS.Contracts.BuildingBlocks.Errors;
global using Paris.RMS.Contracts.BuildingBlocks.Responses;
global using Paris.RMS.Contracts.BuildingBlocks.Results;
global using Swashbuckle.AspNetCore.Annotations;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using static Paris.RMS.Contracts.Constants.Constants.ProblemDetails;
global using static Paris.RMS.ServiceDefaults.Abstractions.ProblemDetailsUtilities;
global using IHttpResult = Microsoft.AspNetCore.Http.IResult;
global using IResult = Paris.RMS.Contracts.BuildingBlocks.Results.IResult;
