global using System.ComponentModel.DataAnnotations;
global using Asp.Versioning;
global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using Paris.RMS.API.Abstractions;
global using Paris.RMS.Contracts.BuildingBlocks.Errors;
global using Paris.RMS.Contracts.BuildingBlocks.Responses;
global using Paris.RMS.Contracts.BuildingBlocks.Results;
global using Paris.RMS.Contracts.BuildingBlocks.Validators;
global using Paris.RMS.Infrastructures.Services;
global using Paris.RMS.Persistences;
global using Paris.RMS.ServiceDefaults;
global using Paris.RMS.UseCases;
global using Swashbuckle.AspNetCore.Annotations;
global using static Paris.RMS.API.Abstractions.ProblemDetailsUtilities;
global using static Paris.RMS.Contracts.Constants.Constants.ProblemDetails;
global using IHttpResult = Microsoft.AspNetCore.Http.IResult;
global using IResult = Paris.RMS.Contracts.BuildingBlocks.Results.IResult;
