global using System.Linq.Expressions;
global using System.Reflection;
global using System.Security.Claims;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Paris.RMS.Contracts.BuildingBlocks.CQRS;
global using Paris.RMS.Contracts.BuildingBlocks.CQRS.OffsetPages;
global using Paris.RMS.Contracts.BuildingBlocks.DDD.Specifications;
global using Paris.RMS.Contracts.BuildingBlocks.Responses;
global using Paris.RMS.Contracts.BuildingBlocks.Results;
global using Paris.RMS.Contracts.BuildingBlocks.Validators;
global using Paris.RMS.Contracts.Utilities;
global using Paris.RMS.Domains.Products;
global using Paris.RMS.Domains.Systems;
global using Paris.RMS.Domains.Systems.Repositories;
global using Paris.RMS.Domains.Users;
global using Paris.RMS.UseCases.UserServices;
global using static Paris.RMS.Contracts.BuildingBlocks.Errors.Error;
global using static Paris.RMS.Contracts.Utilities.PageUtilities;
global using IResult = Paris.RMS.Contracts.BuildingBlocks.Results.IResult;
