global using System.Buffers;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq.Dynamic.Core;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.Json.Serialization.Metadata;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Paris.RMS.Contracts.BuildingBlocks.CQRS.OffsetPages;
global using Paris.RMS.Contracts.BuildingBlocks.Databases;
global using Paris.RMS.Contracts.BuildingBlocks.DDD;
global using Paris.RMS.Contracts.BuildingBlocks.DDD.Specifications;
global using Paris.RMS.Contracts.BuildingBlocks.Errors;
global using Paris.RMS.Contracts.BuildingBlocks.EventBus.Events;
global using Paris.RMS.Contracts.BuildingBlocks.Responses;
global using Paris.RMS.Contracts.BuildingBlocks.Results;
global using Paris.RMS.Contracts.Exceptions;
global using Paris.RMS.Contracts.Utilities;
global using static Paris.RMS.Contracts.Constants.Constants.CustomType;
global using static Paris.RMS.Contracts.Constants.Constants.ProblemDetails;
global using ValidationResult = Paris.RMS.Contracts.BuildingBlocks.Results.ValidationResult;
