global using System.Linq.Expressions;
global using System.Reflection;
global using MediatR;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Paris.RMS.Contracts.BuildingBlocks.CQRS;
global using Paris.RMS.Contracts.BuildingBlocks.CQRS.CusorPages;
global using Paris.RMS.Contracts.BuildingBlocks.CQRS.OffsetPages;
global using Paris.RMS.Contracts.BuildingBlocks.Databases;
global using Paris.RMS.Contracts.BuildingBlocks.DDD.Specifications;
global using Paris.RMS.Contracts.BuildingBlocks.DDD.Specifications.Common;
global using Paris.RMS.Contracts.BuildingBlocks.Responses;
global using Paris.RMS.Contracts.BuildingBlocks.Results;
global using Paris.RMS.Contracts.Utilities;
global using Paris.RMS.Domains.Products;
global using Paris.RMS.Domains.Systems;
global using Paris.RMS.Domains.Users;
global using Paris.RMS.Persistences.Configurations;
global using Paris.RMS.Persistences.Databases;
global using Paris.RMS.Persistences.Pipelines;
global using Paris.RMS.Persistences.Repositories;
global using Paris.RMS.Persistences.Repositories.Products;
global using Paris.RMS.Persistences.UnitOfWorks;
global using Paris.RMS.UseCases.UserServices;
global using static Microsoft.EntityFrameworkCore.EntityState;
global using static Microsoft.EntityFrameworkCore.QueryTrackingBehavior;
global using static Paris.RMS.Persistences.Configurations.ConfigurationConstants;
global using SystemDateTimeOffset = System.DateTimeOffset;
